# Generated by Django 3.1.7 on 2022-11-07 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('host_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_cn', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('hight', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('name_cn', models.CharField(max_length=50)),
                ('location_cn', models.CharField(max_length=50)),
                ('gym', models.CharField(max_length=50)),
                ('logo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.TextField(null=True)),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('rebound', models.IntegerField()),
                ('o_rebound', models.IntegerField()),
                ('d_rebound', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('steal', models.IntegerField()),
                ('block', models.IntegerField()),
                ('foul', models.IntegerField()),
                ('turnover', models.IntegerField()),
                ('field_goals_attempted', models.IntegerField()),
                ('field_goals_made', models.IntegerField()),
                ('three_points_attempt', models.IntegerField()),
                ('three_points_made', models.IntegerField()),
                ('free_throws_attempted', models.IntegerField()),
                ('free_throws_made', models.IntegerField()),
                ('belong_to_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.game')),
                ('belong_to_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minute', models.IntegerField()),
                ('score', models.IntegerField()),
                ('rebound', models.IntegerField()),
                ('o_rebound', models.IntegerField()),
                ('d_rebound', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('steal', models.IntegerField()),
                ('block', models.IntegerField()),
                ('foul', models.IntegerField()),
                ('turnover', models.IntegerField()),
                ('field_goals_attempted', models.IntegerField()),
                ('field_goals_made', models.IntegerField()),
                ('three_points_attempt', models.IntegerField()),
                ('three_points_made', models.IntegerField()),
                ('free_throws_attempted', models.IntegerField()),
                ('free_throws_made', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('belong_to_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.game')),
                ('belong_to_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_team', to='core.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_team', to='core.team'),
        ),
        migrations.CreateModel(
            name='CommentStar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('belong_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.game')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('belong_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.game')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_cn', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('photo', models.TextField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
        ),
    ]
