# Generated by Django 3.1.7 on 2022-11-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='subarea',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PlayerHonors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=50)),
                ('first_team', models.CharField(max_length=50)),
                ('second_team', models.CharField(max_length=50)),
                ('third_team', models.CharField(max_length=50)),
                ('d_first_team', models.CharField(max_length=50)),
                ('d_second_team', models.CharField(max_length=50)),
                ('d_third_team', models.CharField(max_length=50)),
                ('amvp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amvp_player', to='core.player')),
                ('assist_king', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_king_player', to='core.player')),
                ('block_king', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_king_player', to='core.player')),
                ('dpoy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpoy_player', to='core.player')),
                ('mvp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_player', to='core.player')),
                ('rebound_king', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebound_king_player', to='core.player')),
                ('score_king', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_king_player', to='core.player')),
                ('smoy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smoy_player', to='core.player')),
                ('steal_king', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steal_king_player', to='core.player')),
            ],
        ),
    ]
