# Generated by Django 3.1.7 on 2022-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221128_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guest_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='host_score',
            field=models.IntegerField(null=True),
        ),
    ]
