# Generated by Django 3.1.7 on 2022-12-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221128_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstats',
            old_name='belong_to_player',
            new_name='belong_to_team',
        ),
        migrations.AddField(
            model_name='commentstar',
            name='for_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player'),
        ),
    ]
