# Generated by Django 3.1.7 on 2022-12-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_authrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
