# Generated by Django 3.1.7 on 2022-12-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221223_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guest_score_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='guest_score_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='guest_score_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='guest_score_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='host_score_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='host_score_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='host_score_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='host_score_4',
            field=models.IntegerField(null=True),
        ),
    ]
